# Generated by Django 4.0.6 on 2022-07-10 00:20

import api.utils
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boletas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('expirationDate', models.DateField(default=datetime.datetime(2022, 8, 7, 0, 20, 12, 428633))),
                ('cost', models.PositiveIntegerField()),
                ('statusPayment', models.CharField(max_length=50)),
                ('barCode', models.CharField(blank=True, default=api.utils.create_bar_code, editable=False, max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=16)),
                ('payment', models.PositiveIntegerField()),
            ],
        ),
    ]
