# Generated by Django 2.2 on 2022-07-09 22:17

import api.utils
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boletas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('expirationDate', models.DateField(default=datetime.datetime(2022, 8, 6, 22, 17, 27, 829822))),
                ('cost', models.PositiveIntegerField()),
                ('statusPayment', models.CharField(max_length=50)),
                ('barCode', models.CharField(blank=True, default=api.utils.create_bar_code, editable=False, max_length=16, unique=True)),
            ],
        ),
    ]
