# Generated by Django 2.2 on 2022-07-09 22:21

import api.utils
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletas',
            name='barCode',
            field=models.CharField(blank=True, default=api.utils.create_bar_code, editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='boletas',
            name='expirationDate',
            field=models.DateField(default=datetime.datetime(2022, 8, 6, 22, 21, 13, 804727)),
        ),
    ]
