# Generated by Django 2.2 on 2022-07-09 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletas',
            name='expirtaionDate',
            field=models.DateField(verbose_name=datetime.datetime(2022, 8, 6, 17, 52, 25, 805623)),
        ),
    ]
