# Generated by Django 4.0.6 on 2022-07-10 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_transactions_alter_boletas_expirationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletas',
            name='expirationDate',
            field=models.DateField(default=datetime.datetime(2022, 8, 7, 7, 34, 8, 545744)),
        ),
        migrations.AlterField(
            model_name='boletas',
            name='statusPayment',
            field=models.CharField(blank=True, default='pending', editable=False, max_length=50),
        ),
    ]
