# Generated by Django 2.2 on 2022-07-09 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220709_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletas',
            name='expirtaionDate',
            field=models.DateField(default=datetime.datetime(2022, 8, 6, 18, 0, 23, 801857)),
        ),
    ]
