# Generated by Django 2.2 on 2022-07-09 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220709_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boletas',
            name='expirtaionDate',
        ),
        migrations.AddField(
            model_name='boletas',
            name='expirationDate',
            field=models.DateField(default=datetime.datetime(2022, 8, 6, 19, 53, 14, 499692)),
        ),
    ]
