# Generated by Django 2.2 on 2022-07-09 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220709_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletas',
            name='expirationDate',
            field=models.DateField(default=datetime.datetime(2022, 8, 6, 19, 58, 52, 828219)),
        ),
        migrations.AlterField(
            model_name='boletas',
            name='urlBarCode',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
