# Generated by Django 2.2 on 2022-07-09 20:03

import api.utils
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220709_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boletas',
            name='urlBarCode',
        ),
        migrations.AddField(
            model_name='boletas',
            name='barCode',
            field=models.CharField(blank=True, default=api.utils.create_bar_code, editable=False, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='boletas',
            name='expirationDate',
            field=models.DateField(default=datetime.datetime(2022, 8, 6, 20, 3, 51, 265879)),
        ),
    ]
