# Generated by Django 2.2 on 2022-07-09 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220709_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletas',
            name='expirationDate',
            field=models.DateField(default=datetime.datetime(2022, 8, 6, 20, 43, 23, 220008)),
        ),
    ]
