# Generated by Django 2.2 on 2022-07-09 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220709_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boletas',
            name='barCode',
        ),
        migrations.AlterField(
            model_name='boletas',
            name='expirationDate',
            field=models.DateField(default=datetime.datetime(2022, 8, 6, 22, 14, 41, 259500)),
        ),
    ]
